### ISSUE TITLE
Commands for Mi Robot time out on latest Mi Robot firmware

### ISSUE THREAD

**Issue by jghaanstra** [aholstenson/miio#59] opened 2017-08-12 15:35 UTC
I recently updated to the latest firmware of the Mi Robot (3.3.9_003077). After the update pretty much all commands send using this miio library are timing out. It seems with this firmware update the Mi Robot would benefit from a longer time out configuration when sending the requests.

```
λ miio --discover
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 51xx03
Model info: Unknown
Address: 192.168.0.133 (Mi-Robot)
Token: 46625a3xxxx66747948 via stored token
Support: Unknown

λ miio --inspect 51xx03
 INFO  Attempting to inspect 51xx03
 WARNING  Could not find device
```

My network is fine, using the Mi Home app the reaction is instant.

**Comment by kokarn** [comment] 2017-08-31 19:39
This is a duplicate of #40. Over there you can find out how the use the library with the latest firmware

**Comment by jghaanstra** [comment] 2017-08-31 20:16
No it's not. Issue #40 is about wrong tokens. I have a working token retrieved from the miio2.db and commands do get through sometimes but most commands time out because the robot does not timely respond.

**Comment by kokarn** [comment] 2017-08-31 20:24
Ah, seems you are right. I got a bit confused because it seems like #40 includes some timeout issues as well from some people.

**Comment by aholstenson** [comment] 2017-09-01 07:50
This has been an issue with the vacuum for me as well, but on an older firmware. Do commands work if you do not use the `miio` client? In any case I think it's a good idea to increase the time out.

**Comment by jghaanstra** [comment] 2017-09-01 08:33
Yeah looks like it, not sure if I have the control command correctly but it seems to be unable to find the device.

`λ miio --control 192.168.0.133 --token 5936477axxxx34d6a4256 --method find_me
 INFO  Attempting to control 192.168.0.133

 WARNING  Could not find device`

**Comment by jaumard** [comment] 2017-09-02 17:40
Same here :( token retrieved from miio2.db but command just timeout (even if I increase it just to test) :(

**Comment by mortocks** [comment] 2017-09-04 12:12
+1  for firmware 3.3.9_003077
```
sudo miio --update 192.168.0.109 --token MY_TOKEN
INFO  Attempting to update 192.168.0.109
WARNING  Could not find device
```

Got the token just fine but then nothing else works.

**Comment by tobsch** [comment] 2017-09-08 10:14
+1

**Comment by jghaanstra** [comment] 2017-09-10 08:16
I edited the cli index.js and increased the time out there. This changes the error from "Could not find device" to this:
```
λ miio --control 192.168.0.133 --token 5936xxxxx4256 --method find_me
 INFO  Attempting to control 192.168.0.133

 ERROR  Can't connect to device, error while connecting:  Call to device timed out
```

**Comment by jghaanstra** [comment] 2017-10-07 21:34
@aholstenson is there any news concerning this issue? Or are you not actively maintaining this library anymore?

**Comment by linuxlurak** [comment] 2017-10-13 12:20
miio --discover
 INFO  Discovering devices. Press Ctrl+C to stop.

```
Device ID: [cut out]
Model info: Unknown 
Address: 192.168.8.1 
Token: [cut out] via auto-token
Support: Unknown

(node:16181) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Call to device timed out
(node:16181) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
and

```
miio --configure --ssid [cut out] --passwd [cut out] --token [cut out] 
 INFO  Configuring all devices

 WARNING  No devices were configured
```

**Comment by aholstenson** [comment] 2017-11-04 17:40
The latest release has a larger time out, which might help, but I'm not very hopeful. Connectivity seems sporadic over the local network.

Debugging of the code and pull requests are very welcome if this issue is still a problem.

**Closed by aholstenson** 2017-11-04 17:40 UTC
