### ISSUE TITLE
 Unhandled promise rejection 

### ISSUE THREAD

**Issue by xuqisheng** [aholstenson/miio#32] opened 2017-05-24 01:37 UTC
homebridge-miio have some error log, it throw from your miio module？ ☘️

```{r, engine='bash', count_lines}
[5/22/2017, 8:35:42 PM] [homebridge-miio.XiaomiMiio] Couldn't investigate device { id: 56301635,
  address: '192.168.0.101',
  port: 54321,
  token: '00000000000000000000000000000000',
  lastSeen: 1495456538258,
  writeOnly: true } Error: Timeout
    at _ensureToken.then (/usr/lib/node_modules/homebridge-miio/node_modules/miio/lib/device.js:223:23)
(node:1970) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'model' of undefined
[5/22/2017, 8:35:42 PM] [homebridge-miio.XiaomiMiio] Couldn't investigate device { id: 48607372,
  address: '192.168.0.107',
  port: 54321,
  token: '6eccb9043ba1af9de7359c6ff7733eec',
  lastSeen: 1495456538260,
  writeOnly: true } Error: Timeout
    at _ensureToken.then (/usr/lib/node_modules/homebridge-miio/node_modules/miio/lib/device.js:223:23)
[5/22/2017, 8:35:42 PM] [homebridge-miio.XiaomiMiio] Couldn't investigate device { id: 52811490,
  address: '192.168.0.108',
  port: 54321,
  token: '19533b578d009fc04ae67293ea3ad662',
  lastSeen: 1495456538261,
  writeOnly: true } Error: Timeout
    at _ensureToken.then (/usr/lib/node_modules/homebridge-miio/node_modules/miio/lib/device.js:223:23)
(node:1970) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'model' of undefined
(node:1970) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'model' of undefined
[5/22/2017, 8:35:42 PM] [homebridge-miio.XiaomiMiio] Couldn't investigate device { id: 54171853,
  address: '192.168.0.102',
  port: 54321,
  token: '99695a066dec30ba352f37167e5993d5',
  lastSeen: 1495456538261,
  writeOnly: true } Error: Timeout
    at _ensureToken.then (/usr/lib/node_modules/homebridge-miio/node_modules/miio/lib/device.js:223:23)
(node:1970) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'model' of undefined
[5/22/2017, 8:35:42 PM] [homebridge-miio.XiaomiMiio] Couldn't investigate device { id: 52813292,
  address: '192.168.0.104',
  port: 54321,
  token: 'ad48f6c715ff3b778c4c5c13601d1d77',
  lastSeen: 1495456538262,
  writeOnly: true } Error: Timeout
    at _ensureToken.then (/usr/lib/node_modules/homebridge-miio/node_modules/miio/lib/device.js:223:23)
(node:1970) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot read property 'model' of undefined
[5/22/2017, 8:35:43 PM] [homebridge-miio.XiaomiMiio] Couldn't investigate device { id: 52773248,
  address: '192.168.0.110',
  port: 54321,
  token: '7c1cd402f2298ca4a58da2723c099f19',
  lastSeen: 1495456538261,
  writeOnly: true } Error: Timeout
    at _ensureToken.then (/usr/lib/node_modules/homebridge-miio/node_modules/miio/lib/device.js:223:23)
(node:1970) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot read property 'model' of undefined
(node:1970) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: Call to device timed out

```

**Comment by aholstenson** [comment] 2017-05-24 06:45
This is thrown because miio uses promises for calls, the caller has to handle the error case or Node will show that warning. The issue is probably on the homebridge-miio side of things, but its on such an old version of miio that it's hard to test.

As error handling is up to the user of the library I'm closing this issue, please open an issue in homebridge-miio about this instead.

**Closed by aholstenson** 2017-05-24 06:45 UTC
